DATASET:
  NAME: InferenceSubtitleFrameDetectionDataset
  ARGS:
    video_path: !env ${DATA_DIR}/video/damingwangchao/E01.mp4
    intervals: 5
    select_range: [0.2, 0.8, 0.8, 1]
    PREPROCESSOR:
      NAME: SubtitleFrameDetectionPreprocessor
      ARGS:
        image_width: 960
        image_height: 320
        add_positions: True
    TRANSFORMS:
      - NAME: SubtitleFrameDetectionNormalize
        ARGS:
          mean: [0, 0, 0]
          std: [255, 255, 255]
      - NAME: SubtitleFrameDetectionConcat
        ARGS: {}
      - NAME: SubtitleFrameDetectionTranspose
        ARGS: {}
      - NAME: SubtitleFrameDetectionToTensor
        ARGS: {}

MODEL:
  NAME: SubtitleFrameDetectionModel
  ARGS:
    device: cuda
    model_path: !env ${OUTPUT_DIR}/checkpoints/base/base_39.pth
    input_channels: 8
    block: BasicBlock
    layers: [2, 2, 2, 2]
    num_classes: 1000
    dcn: null
    stage_with_dcn: (False, False, False, False)

POSTPROCESSOR:
  NAME: InferenceSubtitleFrameDetectionPostprocessor
  ARGS: {}

HYPER:
  OTHERS:
    log_dir: !env ${OUTPUT_DIR}/logs
    fps: 25
  INFERENCE:
    batch_size: 16
    num_workers: 8
    pin_memory: True
    drop_last: True
    shuffle: False

